// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MockVerifier
 * @dev Simulates an EZKL Verifier contract for the POC.
 * In production, this would be auto-generated by ezkl.verify
 */
contract MockVerifier {
    function verify(
        uint256[] calldata pubInputs,
        bytes calldata proof
    ) external pure returns (bool) {
        // In a real verifier, this checks the cryptographic proof.
       
        return proof.length > 0;
    }
}